// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module min3 (
        ap_ready,
        a,
        b,
        c,
        ap_return
);


output   ap_ready;
input  [31:0] a;
input  [31:0] b;
input  [31:0] c;
output  [31:0] ap_return;

wire   [0:0] icmp_ln7_fu_26_p2;
wire   [31:0] select_ln7_fu_32_p3;
wire   [0:0] icmp_ln11_fu_40_p2;

assign ap_ready = 1'b1;

assign ap_return = ((icmp_ln11_fu_40_p2[0:0] === 1'b1) ? c : select_ln7_fu_32_p3);

assign icmp_ln11_fu_40_p2 = (($signed(select_ln7_fu_32_p3) > $signed(c)) ? 1'b1 : 1'b0);

assign icmp_ln7_fu_26_p2 = (($signed(b) < $signed(a)) ? 1'b1 : 1'b0);

assign select_ln7_fu_32_p3 = ((icmp_ln7_fu_26_p2[0:0] === 1'b1) ? b : a);

endmodule //min3
