// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _min3_HH_
#define _min3_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct min3 : public sc_module {
    // Port declarations 5
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<16> > a;
    sc_in< sc_lv<16> > b;
    sc_in< sc_lv<16> > c;
    sc_out< sc_lv<16> > ap_return;


    // Module declarations
    min3(sc_module_name name);
    SC_HAS_PROCESS(min3);

    ~min3();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<1> > icmp_ln7_fu_26_p2;
    sc_signal< sc_lv<16> > select_ln7_fu_32_p3;
    sc_signal< sc_lv<1> > icmp_ln11_fu_40_p2;
    static const sc_logic ap_const_logic_1;
    static const bool ap_const_boolean_1;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_ap_ready();
    void thread_ap_return();
    void thread_icmp_ln11_fu_40_p2();
    void thread_icmp_ln7_fu_26_p2();
    void thread_select_ln7_fu_32_p3();
};

}

using namespace ap_rtl;

#endif
