-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity min3 is
port (
    ap_ready : OUT STD_LOGIC;
    a : IN STD_LOGIC_VECTOR (31 downto 0);
    b : IN STD_LOGIC_VECTOR (31 downto 0);
    c : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of min3 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal icmp_ln7_fu_26_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln7_fu_32_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln11_fu_40_p2 : STD_LOGIC_VECTOR (0 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return <= 
        c when (icmp_ln11_fu_40_p2(0) = '1') else 
        select_ln7_fu_32_p3;
    icmp_ln11_fu_40_p2 <= "1" when (signed(select_ln7_fu_32_p3) > signed(c)) else "0";
    icmp_ln7_fu_26_p2 <= "1" when (signed(b) < signed(a)) else "0";
    select_ln7_fu_32_p3 <= 
        b when (icmp_ln7_fu_26_p2(0) = '1') else 
        a;
end behav;
